title: Now-here
default_lang: es
author:
  name: NowHere
  email: contacto@estudionow-here.mx
  url: 'http://estudionow-here.mx/'
taxonomies:
  - category
  - tag
metadata:
  description: 'Estudio Now Here'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
contact:
  address: Mérida
  phone: '(999) 114-6345'
  email: contacto@estudionow-here.mx
header:
  facebook: 'https://www.facebook.com/estudionow.here'
  instagram: 'https://www.instagram.com/estudionow.here'
  behance: 'https://www.behance.net/estudionow-here'
  id: estudionow.here
