title: My Site
author:
  name: Joe Bloggs
  email: 'joe@test.com'
  url: 'www.google.fr' 
contact:
  address: "Suite 306\n37 Swanston Street\nMelbourne VIC 3000"
  phone: +3333
  email: dedewde@gmail.fr
social:
  instagram: dedwed.fr
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'

