title: Now-here
default_lang: es
author:
  name: NowHere
  email: estudionow.here@gmail.com
  url: www.google.fr
taxonomies:
  - category
  - tag
metadata:
  description: 'Estudio Now Here'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
contact:
  address: "Suite 306\n37 Swanston Street\nMelbourne VIC 3000"
  phone: (999) 114-6345
  email: estudionow.here@gmail.com
social:
  instagram: dedwed.fr
