title: Now-here
default_lang: es
author:
  name: NowHere
  email: contacto@estudionow-here.mx
  url: 'http://estudionow-here.mx/'
taxonomies:
  - category
  - tag
metadata:
  description: 'Now-Here es un estudio creativo ubicado en Mérida, Yucatán.  Desarrollamos estrategias de comunicación para la creación y el desarrollo de proyectos culturales y comerciales, a través de diferentes disciplinas.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
contact:
  address: 'C-59 #372-A x 40 y 42 Col. Centro - Mérida'
  phone: '(999) 114-63-45'
  phone2: '(999) 264-19-36'
  email: contacto@estudionow-here.mx
header:
  facebook: 'https://www.facebook.com/estudionow.here'
  instagram: 'https://www.instagram.com/estudionow.here'
  behance: 'https://www.behance.net/estudionow-here'
  id: estudionow.here
