@extends:
    '@parent'

form:
    fields:
        content:
            fields:
                contact.phone:
                  type: text
                  label: Phone
                contact.address:
                  type: text
                  label: Address
                header.facebook:
                  type: text
                  label: Facebook
                header.instagram:
                  type: text
                  label: Instagram
                header.behance:
                  type: text
                  label: Behance
                header.id:
                  type: text
                  label: Facebook Id
